[package]
name = "transparent_window"
version = "0.1.0"
edition = "2021"

# ...其他配置...
build = "build.rs"

[dependencies]
chrono = "0.4.40"
druid = "0.8.3"
image = "0.25.6"
serde_json = "1.0.140"
tokio-test = "0.4.4"
yahoo_finance_api = "3.0.0"

[build-dependencies]
winres = "0.1"